name = "cidb hugo starter theme"
license = "MIT"
licenselink = "https://github.com/ci-db/hugo-theme-starter/blob/master/LICENSE.md"
description = "Modern."
homepage = "https://github.com/ci-db/hugo-theme-starter"
tags = ["blog", "plain", "blank", "starter"]
features = ["blog"]
min_version = 1.0

[author]
  name = "bluffy"
  homepage = "https://github.com/bluffy"
